"""Database models for Finlytics."""
from datetime import datetime
from typing import Optional
from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, Text, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()


class Trade(Base):
    """Trade execution record."""
    __tablename__ = "trades"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False)
    symbol = Column(String(20), nullable=False, index=True)
    side = Column(String(10), nullable=False)  # BUY or SELL
    quantity = Column(Float, nullable=False)
    price = Column(Float, nullable=False)
    commission = Column(Float, default=0.0)
    strategy = Column(String(100))
    order_id = Column(String(100), unique=True)
    status = Column(String(20), default="pending")  # pending, filled, cancelled, rejected
    
    def __repr__(self):
        return f"<Trade {self.symbol} {self.side} {self.quantity}@{self.price}>"


class Position(Base):
    """Current portfolio positions."""
    __tablename__ = "positions"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False, unique=True, index=True)
    quantity = Column(Float, nullable=False)
    avg_entry_price = Column(Float, nullable=False)
    current_price = Column(Float)
    unrealized_pnl = Column(Float, default=0.0)
    realized_pnl = Column(Float, default=0.0)
    last_updated = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def __repr__(self):
        return f"<Position {self.symbol} qty={self.quantity}>"


class Signal(Base):
    """Trading signals generated by analysis."""
    __tablename__ = "signals"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    signal_type = Column(String(10), nullable=False)  # BUY, SELL, HOLD
    strength = Column(Float)  # 0.0 to 1.0
    strategy = Column(String(100))
    indicators = Column(Text)  # JSON string of indicator values
    price_at_signal = Column(Float)
    target_price = Column(Float)
    stop_loss = Column(Float)
    executed = Column(Boolean, default=False)
    
    def __repr__(self):
        return f"<Signal {self.symbol} {self.signal_type} strength={self.strength}>"


class MarketData(Base):
    """Historical market data."""
    __tablename__ = "market_data"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    symbol = Column(String(20), nullable=False, index=True)
    open = Column(Float)
    high = Column(Float)
    low = Column(Float)
    close = Column(Float, nullable=False)
    volume = Column(Float)
    
    def __repr__(self):
        return f"<MarketData {self.symbol} {self.timestamp} close={self.close}>"


class PortfolioSnapshot(Base):
    """Portfolio value snapshots over time."""
    __tablename__ = "portfolio_snapshots"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    total_value = Column(Float, nullable=False)
    cash = Column(Float, nullable=False)
    positions_value = Column(Float, nullable=False)
    daily_pnl = Column(Float, default=0.0)
    total_pnl = Column(Float, default=0.0)
    num_positions = Column(Integer, default=0)
    
    def __repr__(self):
        return f"<PortfolioSnapshot {self.timestamp} value={self.total_value}>"


class RiskMetrics(Base):
    """Risk metrics tracking."""
    __tablename__ = "risk_metrics"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    portfolio_var = Column(Float)  # Value at Risk
    sharpe_ratio = Column(Float)
    max_drawdown = Column(Float)
    volatility = Column(Float)
    beta = Column(Float)
    exposure = Column(Float)  # Total market exposure
    
    def __repr__(self):
        return f"<RiskMetrics {self.timestamp} VaR={self.portfolio_var}>"


class AgentStatus(Base):
    """Agent health and status tracking."""
    __tablename__ = "agent_status"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    agent_name = Column(String(100), nullable=False, unique=True, index=True)
    status = Column(String(20), default="stopped")  # running, stopped, error
    last_heartbeat = Column(DateTime, default=datetime.utcnow)
    events_processed = Column(Integer, default=0)
    errors_count = Column(Integer, default=0)
    last_error = Column(Text)
    
    def __repr__(self):
        return f"<AgentStatus {self.agent_name} {self.status}>"
